const lyricsData = {
    "FEIN":  [
        { time: 0, text: "[Intro]" },
        { time: 15, text: "Just come outside for the night (yeah)" },
        { time: 19, text: "Take your time, get your light (yeah)" },
        { time: 22, text: "Johnny Dang, huh-uh" },
        { time: 25, text: "I been out geekin'" },
        { time: 28, text: "Bitch" },
        { time: 30, text: "Fein', fein', fein', fein'-fein' (yeah)" },
        { time: 32, text: "Fein', fein', fein', fein'-fein' (yeah)" },
        { time: 35, text: "Fein', fein', fein', fein'-fein'" },
        { time: 38, text: "Fein', fein', fein', fein' (yeah)" },
        { time: 44, text: "The career's more at stake when you in your prime (at stake)" },
        { time: 47, text: "Fuck that paper, baby, my face on the dotted line (dot, yeah)" },
        { time: 50, text: "I been flyin' out of town for some peace of mind (yeah, yeah, bitch)" },
        { time: 54, text: "It's like always they just want a piece of mine (ah)" },
        { time: 57, text: "I been focused on the future, never on right now (ah)" },
        { time: 61, text: "But I'm sippin' that kombucha, either pink or brown (it's lit)" },
        { time: 64, text: "I'm the one that introduced you to the you right now (mm, let's go)" },
        { time: 68, text: "Oh my God, that bitch bite (that bitch bite)" },
        { time: 71, text: "But alright (alright), tryna vibe (tryna vibe this)" },
        { time: 74, text: "In the night, come alive" },
        { time: 78, text: "Ain't asleep, ain't a-, ain't a-, ain't-ain't-ain't-" },
        { time: 82, text: "Fein', fein', fein', fein'-fein'" },
        { time: 85, text: "Fein', fein', fein', fein'-fein'" },
        { time: 88, text: "Fein', fein', fein', fein'-fein'" },
        { time: 91, text: "Fein', fein', fein', fein', fein'" },
        { time: 95, text: "Fein', fein', fein'" },
        { time: 100, text: "Syrup, whoa, what?" },
        { time: 105, text: "What?" },
        { time: 108, text: "(Homixide, Homixide, Homixide, Homixide) what?" },
        { time: 110, text: "(Yeah, whoa, yeah, yeah)" },
        { time: 113, text: "(Homixide, Homixide, Homixide, Homixide, yeah)" },
        { time: 116, text: "(Yeah, hol' up, yeah)" },
        { time: 118, text: "Yeah, I just been poppin' my shit it's been gettin' live, hol' up (shit)" },
        { time: 121, text: "Yeah, you try to come wrong 'bout this shit, we poppin' ya tires, hol' up (shit)" },
        { time: 124, text: "Uh, hunnid round, whoa, feelin' like I'm on ten" },
        { time: 126, text: "Playin' both sides with these hoes (hol' up)" },
        { time: 129, text: "Shawty, I'm fuckin' yo' friends (hol' up)" },
        { time: 131, text: "I been goin' crazy, shawty, I've been in the deep end" },
        { time: 134, text: "She not innocent, uh, shit, she tryna go" },
        { time: 136, text: "Fein', fein' (talm 'bout), fein', fein'-fein'-fein' (yeah, syrup, oh-oh, what?)" },
        { time: 137, text: "Lảm nhảm gì đó, ngu tiếng anh nên kh hiểu ^.^" }
    ],
    "Khế Ước": [
        { time: 7, text: "Yeah ố ô ố ô" },
        { time: 10, text: "Ố ô ố ô" },
        { time: 13, text: "Ố ô ố ô ố ô ô ô" },
        { time: 15, text: "Ố ô ố ô ố ô ô ô" },
        { time: 17, text: "Ố ô ố ô" },
        { time: 19, text: "Ố ô ố ô" },
        { time: 21, text: "Ố ô ố ô ố ô ô ô" },
        { time: 23, text: "Ố ô ố ô ố ô ô ô" },
        { time: 25, text: "Bao giờ tôi có thể vô tư yeah" },
        { time: 30, text: "Em thì quen sung sướng nên hư từ" },
        { time: 33, text: "Kiểu tôi là đồng cỏ héo khô khan" },
        { time: 38, text: "Em là cơn mưa đá to kinh hoàng" },
        { time: 41, text: "Dù tôi biết (sẽ không tốt đâu)" },
        { time: 43, text: "Nhưng vị môi em (lại có mùi mứt dâu)" },
        { time: 45, text: "Là vị tôi thích nhất giờ vẫn vậy (uh uh)" },
        { time: 49, text: "Lồng ngực tôi (em cắm răng khá sâu)" },
        { time: 52, text: "Thề không đau (là bởi vì quá đau)" },
        { time: 54, text: "But it's worth it (so please don't stop)" },
        { time: 57, text: "Sometimes I wonder" },
        { time: 59, text: "Trời ơi tôi đã vướng vô cái gì thế này" },
        { time: 62, text: "Tôi đã khóc hết nước mắt vì em" },
        { time: 64, text: "Đã dâng hiến xác thân vì em" },
        { time: 66, text: "Để nhận lại gì chứ (để nhận lại gì chứ)" },
        { time: 68, text: "Là giao kèo của quỷ dữ (woah)" },
        { time: 71, text: "Là liều thuốc tôi không thể cai" },
        { time: 72, text: "Là mùi hương của loài hoa có gai" },
        { time: 75, text: "Ồ ố ô ồ ô" },
        { time: 76, text: "Woah ố ô ồ ô" },
        { time: 80, text: "Bao lần tôi cảm thấy chơi vơi (chơi vơi)" },
        { time: 85, text: "Em tìm vui nơi quỷ ma chơi bời (no)" },
        { time: 89, text: "Sáng dậy không quên ghé tai tôi (oh yeah)" },
        { time: 92, text: "Anh mà đi thì đáng lẽ vui rồi" },
        { time: 95, text: "Vậy hay là mình giết nhau (chứ đừng ghét nhau)" },
        { time: 98, text: "Rồi lại nén đau (thà mình giết nhau)" },
        { time: 100, text: "Để mọi thứ kết thúc thật nhanh đi trước khi chúng ta ngoái đầu lại" },
        { time: 104, text: "Còn gì em hỡi" },
        { time: 106, text: "Đừng ai cơi nới để rồi xé xác lẫn nhau vào một tối đẹp trời" },
        { time: 113, text: "Trời ơi tôi (đã vướng vô cái gì thế này)" },
        { time: 116, text: "Tôi đã khóc hết nước mắt vì em" },
        { time: 118, text: "Đã dâng hiến xác thân vì em" },
        { time: 120, text: "Để nhận lại gì chứ (để nhận lại gì chứ)" },
        { time: 122, text: "Là giao kèo của quỷ dữ (uh-uh)" },
        { time: 125, text: "Là liều thuốc tôi không thể cai" },
        { time: 127, text: "Là mùi hương của loài hoa có gai" },
        { time: 129, text: "Ồ ố ô ồ ô" },
        { time: 131, text: "Woah ố ô ồ ô" },
        { time: 133, text: "Đừng chờ đợi đến khi sớm mai" },
        { time: 135, text: "Đường về, đón đưa có ai?" },
        { time: 137, text: "Chuyện tình mình có thật khó phai?" },
        { time: 139, text: "Sao tôi nghe dối lừa bên tai?" },
        { time: 141, text: "Nhìn lại ngày chúng ta có nhau" },
        { time: 143, text: "Chẳng gì ngoài chất chồng nổi đau" },
        { time: 146, text: "Đừng hẹn thề tái hợp kiếp sau" },
        { time: 148, text: "Trong tim em có còn tôi đâu" },
        { time: 167, text: "Chẳng còn gì người ơi" },
        { time: 169, text: "Đừng nói thêm điều lả lơi" },
        { time: 171, text: "Mình chẳng còn gì người ơi" },
        { time: 173, text: "Đừng nói thêm điều lả lơi" },
        { time: 175, text: "Chẳng còn gì người ơi" },
        { time: 177, text: "Đừng nói thêm điều lả lơi" },
        { time: 179, text: "Thà tôi ngạt chết bây giờ" },
        { time: 181, text: "Còn hơn ở lại bên em!" },
        { time: 183, text: "E-E-E-E-E-EE-EM" },
        { time: 190, text: "Còn hơn ở lại bên em!" },
        { time: 193, text: "E-E-E-E-E-EE-EM" },
        { time: 202, text: "Dù anh chết em cũng đâu bận tâm" },
        { time: 204, text: "Cuồng si em cứ như thằng hâm" },
        { time: 206, text: "Để nhận lại gì chứ?" },
        { time: 208, text: "Là giao kèo của quỷ dữ" },
        { time: 210, text: "Là liều thuốc tôi không thể cai" },
        { time: 212, text: "Là mùi hương của loài hoa có gai" },
        { time: 214, text: "Ồ ố ô ồ ô" },
        { time: 219, text: "Đừng chờ đợi đến khi sớm mai" },
        { time: 221, text: "Đường về đón đưa có ai?" },
        { time: 223, text: "Chuyện tình mình có thật khó phai?" },
        { time: 225, text: "Sao tôi nghe dối lừa bên tai?" },
        { time: 227, text: "Nhìn lại ngày chúng ta có nhau" },
        { time: 229, text: "Chẳng gì ngoài chất chồng nỗi đau" },
        { time: 231, text: "Đừng hẹn thề tái hợp kiếp sau" },
        { time: 233, text: "Trong tim em có còn tôi đâu" },
        { time: 235, text: "Ố ỳe" },




    ],
    "Cơn mưa xa dần": [
        { time: 13, text: "Chẳng quan tâm tương lai anh chẳng quan tâm đúng hay sai" },
        { time: 20, text: "Chẳng quan tâm tương lai anh chẳng quan tâm đúng hay sai" },
        { time: 26, text: "Còn đâu đây bao câu ca anh tặng em" },
        { time: 29, text: "Tình yêu em mang cuốn lấp đi bao nhiêu câu ca" },
        { time: 33, text: "Và còn lại đây đôi môi đau thương trong màn đêm" },
        { time: 36, text: "Phải lẻ loi gồng mình bước qua niềm đau khi em rời xa" },
        { time: 39, text: "Cơn mưa rồi lại thêm hey yeh" },
        { time: 43, text: "Cơn mưa rồi lại thêm hey yeh" },
        { time: 47, text: "Cơn mưa rồi lại thêm hey yeh" },
        { time: 50, text: "Cơn mưa rồi lại thêm hey yeh" },
        { time: 53, text: "Vì em đã xa rồi riêng mình anh một giấc mơ này" },
        { time: 57, text: "Vì em đã quên rồi riêng mình anh một giấc mơ" },
        { time: 60, text: "Em bước đi rồi ôi bao cơn mưa" },
        { time: 63, text: "Em bước đi rồi xin hãy xua tan đi em bóng dáng hình em" },
        { time: 67, text: "Em đã mãi rời xa" },
        { time: 68, text: "My girl you're my girl" },
        { time: 72, text: "You are my girl you're my girl" },
        { time: 75, text: "My girl you're my girl" },
        { time: 78, text: "You are my girl you're my girl" },
        { time: 82, text: "Cơn mưa ngang qua" },
        { time: 84, text: "Cơn mưa đi ngang qua" },
        { time: 86, text: "Cơn mưa ngang qua" },
        { time: 87, text: "Cơn mưa mang em đi thật xa" },
        { time: 89, text: "Cơn mưa ngang qua" },
        { time: 91, text: "Cơn mưa đi ngang qua" },
        { time: 92, text: "Cơn mưa ngang qua" },
        { time: 94, text: "Cơn mưa mang em đi thật xa" },
        { time: 95, text: "Cơn mưa rồi lại thêm hey yeh" },
        { time: 99, text: "Cơn mưa rồi lại thêm hey yeh" },
        { time: 102, text: "Cơn mưa rồi lại thêm hey yeh" },
        { time: 106, text: "Cơn mưa rồi lại thêm hey yeh" },
        { time: 109, text: "Vì em đã xa rồi riêng mình anh một giấc mơ này" },
        { time: 112, text: "Vì em đã quên rồi riêng mình anh một giấc mơ" },
        { time: 116, text: "Em bước đi rồi ôi bao cơn mưa" },
        { time: 118, text: "Em bước đi rồi xin hãy xua tan đi em bóng dáng hình em" },
        { time: 122, text: "Em đã mãi rời xa" },
        { time: 124, text: "My girl you're my girl" },
        { time: 126, text: "You are my girl you're my girl" },
        { time: 130, text: "My girl you're my girl" },
        { time: 134, text: "You are my girl you're my girl" },
        { time: 164, text: "Chẳng quan tâm tương lai anh chẳng quan tâm đúng hay sai" },
        { time: 168, text: "Lạc trên con đường dài bao niềm thương nỗi nhớ chia hai" },
        { time: 172, text: "Đè lên trên đôi vai những ngổn ngang ký ức phôi phai" },
        { time: 175, text: "Tình ta sao chông gai" },
        { time: 177, text: "Tình ta sao dừng lại" },
        { time: 179, text: "Chẳng quan tâm tương lai anh chẳng quan tâm đúng hay sai" },
        { time: 181, text: "Lạc trên con đường dài bao niềm thương nỗi nhớ chia hai" },
        { time: 183, text: "Đè lên trên đôi vai những ngổn ngang ký ức phôi phai" },
        { time: 185, text: "Tình ta sao chông gai" },
        { time: 186, text: "Tình ta sao dừng lại" }
    ]
}

export default lyricsData;